# Generated by Django 4.2.9 on 2025-08-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=160)),
                ('url', models.TextField()),
                ('mask', models.IntegerField()),
                ('status', models.IntegerField()),
                ('boxc', models.CharField(max_length=100)),
            ],
        ),
    ]
