# Generated by Django 4.2.9 on 2025-08-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0002_dlr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlr',
            old_name='msc',
            new_name='smsc',
        ),
    ]
