# Generated by Django 4.2.9 on 2025-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0003_rename_msc_dlr_smsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlr',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
