# Generated by Django 4.2.9 on 2025-08-22 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0004_alter_dlr_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlr',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='dlr',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dlr',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
