# Generated by Django 4.2.9 on 2025-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0005_remove_dlr_timestamp_dlr_created_at_dlr_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlr',
            name='timestamp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
