# Generated by Django 4.2.9 on 2025-08-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0006_dlr_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlr',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dlr',
            name='updated_at',
        ),
    ]
