# Generated by Django 4.2.9 on 2025-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0007_remove_dlr_created_at_remove_dlr_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('unique_id', models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='message',
        ),
        migrations.AddField(
            model_name='recipient',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recipient',
            name='personalized_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sms_api.recipient'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms_api.smscampaign'),
            preserve_default=False,
        ),
    ]
