# Generated by Django 4.2.9 on 2025-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0008_messagelog_smscampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
